// <auto-generated />
using EF_Core_Own.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EF_Core_Own.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("EF_Core_Own.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassName");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("EF_Core_Own.Model.Class", b =>
                {
                    b.OwnsOne("EF_Core_Own.Model.Student", "Student", b1 =>
                        {
                            b1.Property<int>("ClassId");

                            b1.Property<int>("Age");

                            b1.Property<int>("Id");

                            b1.Property<string>("Name");

                            b1.ToTable("Classes");

                            b1.HasOne("EF_Core_Own.Model.Class")
                                .WithOne("Student")
                                .HasForeignKey("EF_Core_Own.Model.Student", "ClassId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
